<?php require 'templates/layout/header.phtml' ?>

<div class="container-jugadores">
    <h1>Equipos del fútbol europeo</h1>
    <?php foreach ($equipos as $equipo) : ?>
        <div class="card">
            <div class="jugador-info">
                
            <img src="imagenes/equipos/<?= $equipo->imagen ?>" alt="<?= $equipo->equipo ?>">
                <h2><?= $equipo->equipo . ' ' . $equipo->liga . ' ' . $equipo->pais ?></h2>
                

                <div class="btn-vermas">
                <a href="verjugadores/<?= $equipo->id ?>" class="d-flex justify-content-center btn btn-outline-primary">Ver más</a>
                </div>

            </div>
        </div>
    <?php endforeach ?>
</div>
<p><small>Mostrando <?= $count ?> equipos</small></p>
<?php require 'templates/layout/footer.phtml' ?>

    


