<form action="actualizar" method="POST" class="my-4">
    <input type="hidden" name="id" value="<?= $jugador->id ?>">
    <div class="form-group">
        <label>Nombre</label>
        <input required name="nombre" type="text" class="form-control" value="<?= htmlspecialchars($jugador->nombre) ?>">
        <label>Apellido</label>
        <input required name="apellido" type="text" class="form-control" value="<?= htmlspecialchars($jugador->apellido) ?>">

        <label>Equipo</label>
        <select required name="id_equipo" class="form-control">
            <?php foreach ($equipos as $equipo) : ?>
                <option value="<?= $equipo->id ?>" <?= ($equipo->id == $jugador->id_equipo) ? 'selected' : '' ?>>
                    <?= htmlspecialchars($equipo->equipo) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <label>Imagen del jugador</label>
        <input required name="imagen_jugador" type="file" accept="image/*" class="form-control">
        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </div>
</form>
