<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">

    <title>TUDAI - Lista de jugadores</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav >
            <div class="container-nav">
                
                        
                
            <?php if (!isset($_SESSION['USER_ID'])) : ?>
                       <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>equiposini">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>jugadoresini">Jugadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="login">Login</a>
                        </li>

            <?php else : ?>
                <li class="nav-item">
                        <li class="nav-item">
                        <a class="nav-link" href="<?= BASE_URL ?>equipos">EquiposAdmin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="<?= BASE_URL ?>jugadores">JugadoresAdmin</a>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_USUARIO'] ?>)</a>
                        </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <!-- inicio main container -->
    <main class="container mt-3">